class IconPath:
    normal = [
        'normal/smile',
        'normal/angel',
        'normal/dead',
        'normal/clown',
        'normal/frown',
        'normal/cry',
        'normal/wink',
        'normal/angry',
        'normal/devil',
        'normal/biggrin',
        'normal/oh',
        'normal/tongue',
        'normal/kiss',
        'normal/wonder',
        'normal/agree',
        'normal/donno',
        'normal/hehe',
        'normal/love',
        'normal/surprise',
        'normal/chicken',
        'normal/ass',
        'normal/sosad',
        'normal/good',
        'normal/hoho',
        'normal/kill',
        'normal/bye',
        'normal/z',
        'normal/@',
        'normal/adore',
        'normal/wonder2',
        'normal/banghead',
        'normal/bouncer',
        'normal/bouncy',
        'normal/offtopic',
        'normal/censored',
        'normal/flowerface',
        'normal/shocking',
        'normal/photo',
        'normal/fire',
        'normal/yipes',
        'normal/369',
        'normal/bomb',
        'normal/slick',
        'normal/fuck',
        'normal/no',
        'normal/kill2',
        'normal/dislike',
        'normal/like'
    ]

    pig = [
        'pig/smile',
        'pig/hate',
        'pig/smirk',
        'pig/hehe',
        'pig/mock',
        'pig/clap',
        'pig/sowhat',
        'pig/bye',
        'pig/cut',
        'pig/cook',
        'pig/fry',
        'pig/fan',
        'pig/peanut',
        'pig/wine_connect',
        'pig/whip_special',
        'pig/shocked',
        'pig/read',
        'pig/heard',
        'pig/nope',
        'pig/pointing',
        'pig/argue',
        'pig/drum',
        'pig/speakerphone',
        'pig/sadNangry',
        'pig/angry',
        'pig/knife',
        'pig/arrested',
        'pig/upset',
        'pig/wail',
        'pig/wail2',
        'pig/wail3',
        'pig/sick',
        'pig/dance',
        'pig/dance2',
        'pig/dance3',
        'pig/dance4',
        'pig/dying',
        'pig/surviving',
        'pig/free',
        'pig/lihkg',
        # Hidden
        'pig/wine',
        'pig/cook_connect',
        'pig/knife_connect',
        'pig/whip_connect',
    ]

    dog = [
        'dog/smile',
        'dog/hehe',
        'dog/haha',
        'dog/bye',
        'dog/999',
        'dog/on_hold',
        'dog/phone',
        'dog/FBI',
        'dog/discover',
        'dog/math',
        'dog/photo',
        'dog/telescope',
        'dog/excited',
        'dog/lick',
        'dog/tasty',
        'dog/wet',
        'dog/touch',
        'dog/play',
        'dog/treat',
        'dog/injection',
        'dog/clean',
        'dog/stop',
        'dog/no',
        'dog/realized',
        'dog/scare',
        'dog/angry',
        'dog/zzz',
        'dog/upset',
        'dog/notcry',
        'dog/cry',
        'dog/cheerup',
        'dog/beg_connect',
        'dog/itdog0',
        'dog/itdog1',
        'dog/itdog2',
        'dog/itdog3',
        'dog/itdog4',
        'dog/itdog5',
        'dog/run',
        'dog/bark',
        'dog/escape',
        'dog/beat',
        'dog/fight_connect',
        'dog/npc2',
        'dog/lihkg',
        # Hidden
        'dog/fight1',
        'dog/fight2',
        'dog/fight_connect2',
        'dog/fight_connect3',
    ]

    husky = [
        'husky/smile',
        'husky/hehe',
        'husky/haha',
        'husky/bye',
        'husky/999',
        'husky/FBI',
        'husky/angry',
        'husky/scare',
        'husky/no',
        'husky/touch',
        'husky/wet',
        'husky/lick',
        'husky/zzz',
        'husky/cry',
        'husky/beg',
        'husky/give',
        'husky/itdog1',
        'husky/itdog2',
        'husky/lihkg',
        'husky/fight2',
        'husky/fight1',
        'husky/beat',
        'husky/run',
        'husky/beg_connect',
        'husky/fight_connect',
    ]

    cow = [
        'cow/smile',
        'cow/hehe',
        'cow/sad',
        'cow/sosad',
        'cow/sweat',
        'cow/bye',
        'cow/hair',
        'cow/sadbutsmile',
        'cow/door',
        'cow/grab',
        'cow/no',
        'cow/sleep',
        'cow/plan',
        'cow/scheme',
        'cow/arrogant',
        'cow/cigar',
        'cow/wa',
        'cow/unexpected',
        'cow/ball',
        'cow/medal',
        'cow/power_special',
        'cow/sorry',
        'cow/arrr',
        'cow/bus_special',
        'cow/car',
        'cow/linguistic',
        'cow/lihkg',
        # Hidden
        'cow/grab_connect',
        'cow/crowd',
    ]

    cat = [
        'cat/smile',
        'cat/lick',
        'cat/nap',
        'cat/bye',
        'cat/stare',
        'cat/handup',
        'cat/annoyed',
        'cat/headache',
        'cat/throw',
        'cat/angry',
        'cat/appear',
        'cat/darkness',
        'cat/threat',
        'cat/swipe',
        'cat/rain',
        'cat/shaking',
        'cat/sneeze',
        'cat/mask',
        'cat/disappointed',
        'cat/angel',
        'cat/pussy1',
        'cat/pussy2',
        'cat/stretching',
        'cat/lucky',
        'cat/lihkg',
        # Hidden
        'cat/throw_connect',
    ]

    mouse = [
        'mouse/smile',
        'mouse/miracle_special',
        'mouse/yea',
        'mouse/ohyes',
        'mouse/bye',
        'mouse/fuck',
        'mouse/short',
        'mouse/there',
        'mouse/tea',
        'mouse/cheer',
        'mouse/cheerleading',
        'mouse/love',
        'mouse/vampire_special',
        'mouse/coffin',
        'mouse/cross',
        'mouse/crystalball',
        'mouse/potion',
        'mouse/solution',
        'mouse/gun',
        'mouse/medicine',
        'mouse/how',
        'mouse/what',
        'mouse/scratching',
        'mouse/ohno',
        'mouse/notcry',
        'mouse/cry',
        'mouse/cryalot',
        'mouse/tired',
        'mouse/blah',
        'mouse/sigh',
        'mouse/annoyed',
        'mouse/rubbish',
        'mouse/lihkg',
        # Hidden
        'mouse/special',
        'mouse/vampire',
    ]

    rip = [
        'rip/dog',
        'rip/pig',
        'rip/mouse',
        'rip/cat',
        'rip/cow',
        'rip/flower',
    ]

    # 腦魔
    lm2 = [
        'lm2/abomb',
        'lm2/noodles',
        'lm2/lightbulb',
        'lm2/spinning',
        'lm2/bouncer',
        'lm2/kill',
        'lm2/shield',
        'lm2/hehe',
        'lm2/beer',
        'lm2/no',
        'lm2/shoot',
        'lm2/saber',
        'lm2/danger',
        'lm2/go',
        'lm2/drop',
        'lm2/rise',
        'lm2/kiss2',
        'lm2/kiss',
        'lm2/selfdestruct',
        'lm2/shocking',
    ]

    # 連豬聖誕版
    pigxm = [
        'pigxm/smile',
        'pigxm/hehe',
        'pigxm/mock',
        'pigxm/clap',
        'pigxm/bye',
        'pigxm/cook',
        'pigxm/peanut',
        'pigxm/wine',
        'pigxm/whip_special',
        'pigxm/shocked',
        'pigxm/heard',
        'pigxm/pointing',
        'pigxm/argue',
        'pigxm/drum',
        'pigxm/angry',
        'pigxm/knife',
        'pigxm/arrested',
        'pigxm/upset',
        'pigxm/wail',
        'pigxm/sick',
        'pigxm/dance',
        'pigxm/dance2',
        'pigxm/dance3',
        'pigxm/free',
        'pigxm/lihkg',
    ]

    mapping = {
        'normal': (normal, '普通'),
        'pig': (pig, '連豬'),
        'dog': (dog, '連狗'),
        'husky': (husky, 'Husky'),
        'cow': (cow, '連牛'),
        'cat': (cat, '連貓'),
        'mouse': (mouse, '連鼠'),
        'rip': (rip, 'RIP'),
        'lm2': (lm2, '腦魔'),
        'pigxm': (pigxm, '連豬聖誕版'),
    }

    all = normal + pig + dog + husky + cow + cat + mouse + rip + lm2 + pigxm
